# Generated by Django 4.1.5 on 2023-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
